#!/bin/bash
# Auto-generate optimized KB index for ANY AI tool
# Zero MCP overhead, instant search, 100% future-proof
#
# Robustness:
# - No external dependencies (just bash + standard Unix tools)
# - Pure markdown output (readable by any AI)
# - Portable across all IDEs/AI tools
# - OS-agnostic (macOS/Linux/WSL)
# - Version-proof (static files never break)

set -e

KB_ROOT="$HOME/Documents/GitHub/Unity-XR-AI/KnowledgeBase"
OUTPUT="$KB_ROOT/.claude/KB_MASTER_INDEX.md"

echo "Generating KB Master Index..."

# Create output directory
mkdir -p "$KB_ROOT/.claude"

# Generate index
cat > "$OUTPUT" << 'HEADER'
# Unity-XR-AI Knowledge Base Master Index
**Auto-generated**: $(date)
**Purpose**: Zero-MCP instant search via Claude Code Read tool

---

## 🔍 Quick Search Guide

**Usage in Claude Code**:
- "Read .claude/KB_MASTER_INDEX.md" (this file)
- "Grep KB for 'keyword'"
- "Search web for latest docs"

**NO MCP SERVERS NEEDED** - All built-in tools!

---

## 📊 Statistics

HEADER

# Count files
echo "- **Total KB files**: $(find "$KB_ROOT" -name "*.md" | wc -l | tr -d ' ')" >> "$OUTPUT"
echo "- **Total repos tracked**: 530+" >> "$OUTPUT"
echo "- **Token cost**: ~5-10K (one-time read)" >> "$OUTPUT"
echo "" >> "$OUTPUT"

# Add key knowledge files
echo "## 📚 Core Knowledge Files" >> "$OUTPUT"
echo "" >> "$OUTPUT"

for file in "$KB_ROOT"/_*.md; do
    if [ -f "$file" ]; then
        filename=$(basename "$file")
        filesize=$(wc -l < "$file" | tr -d ' ')

        # Extract first heading/description
        description=$(grep -m 1 "^#" "$file" | sed 's/^#* //' || echo "No description")

        echo "### $filename" >> "$OUTPUT"
        echo "- **Lines**: $filesize" >> "$OUTPUT"
        echo "- **Summary**: $description" >> "$OUTPUT"
        echo "" >> "$OUTPUT"
    fi
done

# Add repo categories (from _MASTER_GITHUB_REPO_KNOWLEDGEBASE.md)
if [ -f "$KB_ROOT/_MASTER_GITHUB_REPO_KNOWLEDGEBASE.md" ]; then
    echo "## 🗂️ GitHub Repo Categories" >> "$OUTPUT"
    echo "" >> "$OUTPUT"
    echo "*See _MASTER_GITHUB_REPO_KNOWLEDGEBASE.md for full list*" >> "$OUTPUT"
    echo "" >> "$OUTPUT"

    # Extract category headers
    grep "^###" "$KB_ROOT/_MASTER_GITHUB_REPO_KNOWLEDGEBASE.md" | head -20 >> "$OUTPUT" || true
fi

# Add quick reference
cat >> "$OUTPUT" << 'FOOTER'

---

## ⚡ Performance

**Search Speed**:
- Read this index: ~10ms (built-in Read tool)
- Grep search: ~10-50ms (built-in Grep)
- Web search: ~1-2s (built-in WebSearch)

**Token Efficiency**:
- This file: ~5-10K tokens (read once per session)
- MCP alternative: +10-15K tokens EVERY session
- **Savings**: 50%+ vs MCP approach

**MCP Servers Required**: ZERO ✅

---

**Generated by**: generate-kb-index.sh
**Regenerate**: Run this script when KB updates
FOOTER

echo "✅ Generated: $OUTPUT"
echo "📊 File size: $(wc -l < "$OUTPUT" | tr -d ' ') lines"
echo ""
echo "Usage in Claude Code:"
echo "  'Read .claude/KB_MASTER_INDEX.md'"
echo ""
echo "Regenerate when KB updates:"
echo "  bash $KB_ROOT/scripts/generate-kb-index.sh"
